# Generated by Django 4.2.10 on 2024-02-15 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='reviewer',
            new_name='purchaser',
        ),
    ]
